"use strict";
const VERSION="1.0.1",SCHEMA="commons.lattice-unit-circles.v1";
function fail(s){throw new Error(s);}
function integer(x,a,b,n){if(!Number.isSafeInteger(x)||x<a||x>b)fail(n+" outside limits");return x;}
function copy(x){return JSON.parse(JSON.stringify(x));}
function abs(x){return x<0n?-x:x;}
function gcd(a,b){a=abs(a);b=abs(b);while(b){const t=a%b;a=b;b=t;}return a;}
function center(x,y,d){if(d===0n)fail("zero center denominator");if(d<0n){x=-x;y=-y;d=-d;}const g=gcd(gcd(x,y),d);return{x:String(x/g),y:String(y/g),denominator:String(d/g)};}
function key(c){return c.x+","+c.y+","+c.denominator;}
function compare(a,b){const ad=BigInt(a.denominator),bd=BigInt(b.denominator),x=BigInt(a.x)*bd-BigInt(b.x)*ad;if(x)return x<0n?-1:1;const y=BigInt(a.y)*bd-BigInt(b.y)*ad;return y<0n?-1:y>0n?1:0;}
function choose(n,k){if(k<0||n<k)return 0n;let a=1n;for(let i=1;i<=k;i++)a=a*BigInt(n-i+1)/BigInt(i);return a;}
function natural(x,n="integer",digits=100){if(typeof x==="number"){if(!Number.isSafeInteger(x)||x<0)fail("unsafe "+n);x=String(x);}if(typeof x!=="string"||!/^(0|[1-9][0-9]*)$/.test(x)||x.length>digits)fail("invalid "+n);return BigInt(x);}
function signed(x,digits=1000){if(typeof x==="number"){if(!Number.isSafeInteger(x))fail("unsafe rational numerator");x=String(x);}if(typeof x!=="string"||! /^-?(0|[1-9][0-9]*)$/.test(x)||x.length>digits)fail("invalid rational numerator");return BigInt(x);}
function fraction(v){if(!Array.isArray(v)||v.length!==2)fail("rational [numerator,denominator] required");let a=signed(v[0]),b=natural(v[1],"rational denominator",1000);if(b===0n)fail("zero rational denominator");const g=gcd(a,b);return[a/g,b/g];}
function add(a,b){const n=a[0]*b[1]+b[0]*a[1],d=a[1]*b[1],g=gcd(n,d);return[String(n/g),String(d/g)];}
function compileLatticeCircles(input){
 if(!input)fail("input required");const rows=integer(input.rows,1,64,"rows"),columns=integer(input.columns,1,64,"columns"),Q=integer(input.denominator,1,8,"denominator"),n=rows*columns;
 const stats={disk_candidates:0,nonzero_offsets:0,unordered_offset_pairs:0,collinear_pairs:0,wrong_radius_pairs:0,unit_radius_pairs:0,kernel_centers:0,anchor_translations:0,candidate_centers:0,discarded_centers_below_three:0,qualified_circles:0,incidences:0,whole_grid_point_pairs_enumerated:0,whole_grid_point_triples_enumerated:0,old_geometry_operations:0};
 const offsets=[];for(let x=-2*Q;x<=2*Q;x++)for(let y=-2*Q;y<=2*Q;y++){stats.disk_candidates++;if((x||y)&&x*x+y*y<=4*Q*Q)offsets.push([x,y]);}stats.nonzero_offsets=offsets.length;
 const kernels=new Map(),q2=BigInt(Q*Q);for(let i=0;i<offsets.length;i++)for(let j=i+1;j<offsets.length;j++){stats.unordered_offset_pairs++;if(stats.unordered_offset_pairs>500000)fail("local-pair budget");const bx=BigInt(offsets[i][0]),by=BigInt(offsets[i][1]),cx=BigInt(offsets[j][0]),cy=BigInt(offsets[j][1]),V=2n*(bx*cy-by*cx);if(V===0n){stats.collinear_pairs++;continue;}const b2=bx*bx+by*by,c2=cx*cx+cy*cy,U=b2*cy-c2*by,W=bx*c2-cx*b2;if(U*U+W*W!==q2*V*V){stats.wrong_radius_pairs++;continue;}stats.unit_radius_pairs++;const c=center(U,W,V),k=key(c);if(!kernels.has(k))kernels.set(k,{center_in_lattice_units:c,offset_indices:new Set(),pair_witnesses:[]});const r=kernels.get(k);r.offset_indices.add(i);r.offset_indices.add(j);r.pair_witnesses.push({offset_indices:[i,j],U:String(U),W:String(W),V:String(V)});}
 const kernel=[...kernels.values()].sort((a,b)=>compare(a.center_in_lattice_units,b.center_in_lattice_units)).map((r,id)=>({id,center_in_lattice_units:r.center_in_lattice_units,offset_indices:[...r.offset_indices].sort((a,b)=>a-b),pair_witnesses:r.pair_witnesses,lattice_points_including_origin:r.offset_indices.size+1}));
 stats.kernel_centers=kernel.length;
 if(n*kernel.length>2000000)fail("anchor-translation budget");
 const candidates=new Map();for(let x=0;x<rows;x++)for(let y=0;y<columns;y++){const point=x*columns+y;for(const r of kernel){stats.anchor_translations++;const c=r.center_in_lattice_units,d=BigInt(c.denominator),C=center(BigInt(c.x)+BigInt(x)*d,BigInt(c.y)+BigInt(y)*d,d*BigInt(Q)),k=key(C);if(!candidates.has(k)){if(candidates.size>=250000)fail("candidate-center budget");candidates.set(k,{center:C,members:new Set(),first_source:{anchor_point:point,kernel_center:r.id}});}candidates.get(k).members.add(point);}}
 stats.candidate_centers=candidates.size;
 let prefix=0n;const pointCircles=Array.from({length:n},()=>[]),hist=new Map();
 const circles=[...candidates.values()].filter(r=>{if(r.members.size<3){stats.discarded_centers_below_three++;return false;}return true;}).sort((a,b)=>compare(a.center,b.center)).map((r,id)=>{const members=[...r.members].sort((a,b)=>a-b),ct=choose(members.length,3),row={id,center:r.center,members,triple_start:String(prefix),triple_count:String(ct),first_source:r.first_source};prefix+=ct;for(const p of members)pointCircles[p].push(id);stats.incidences+=members.length;hist.set(members.length,(hist.get(members.length)||0)+1);return row;});
 stats.qualified_circles=circles.length;
 return{schema:SCHEMA,version:VERSION,input:copy(input),point_encoding:"id=x*columns+y; actual point=(x/denominator,y/denominator)",offsets,kernel,circles,point_circles:pointCircles,summary:{rows,columns,denominator:Q,point_count:n,kernel_center_count:kernel.length,candidate_center_count:candidates.size,unit_circles_at_least_three:circles.length,total_incidences:stats.incidences,determining_triples:String(prefix),multiplicity_histogram:[...hist].sort((a,b)=>a[0]-b[0]).map(([points,count])=>({points,count})),maximum_incidence:circles.reduce((a,r)=>Math.max(a,r.members.length),0)},construction:stats};
}
function openLatticeCircles(raw){
 if(typeof raw==="string"){if(raw.length>16000000)fail("snapshot limit");raw=JSON.parse(raw);}const s=copy(raw);if(!s||s.schema!==SCHEMA||(s.version!==VERSION&&s.version!=="1.0.0")||!s.input)fail("wrong schema");
 const rows=integer(s.input.rows,1,64,"rows"),columns=integer(s.input.columns,1,64,"columns"),Q=integer(s.input.denominator,1,8,"denominator"),n=rows*columns;
 if(!Array.isArray(s.circles)||s.circles.length>250000||!Array.isArray(s.kernel)||!Array.isArray(s.offsets)||!Array.isArray(s.point_circles)||s.point_circles.length!==n)fail("invalid saved arrays");
 let expected=0n,previous=null;const centerIds=new Map();for(let i=0;i<s.circles.length;i++){const c=s.circles[i];if(c.id!==i||!Array.isArray(c.members)||c.members.length<3)fail("invalid circle");const cn=center(signed(c.center.x),signed(c.center.y),natural(c.center.denominator));if(key(cn)!==key(c.center)||previous&&compare(previous,c.center)>=0)fail("center normalization/order");previous=c.center;centerIds.set(key(c.center),i);let last=-1;for(const p of c.members){integer(p,0,n-1,"member");if(p<=last)fail("member order");last=p;}if(natural(c.triple_start)!==expected||natural(c.triple_count)!==choose(c.members.length,3))fail("triple prefix/count");expected+=BigInt(c.triple_count);}
 for(const list of s.point_circles){if(!Array.isArray(list))fail("invalid point index");let last=-1;for(const id of list){integer(id,0,s.circles.length-1,"circle reference");if(id<=last)fail("point index order");last=id;}}
 const stats={opened_circle_rows:s.circles.length,opened_kernel_rows:s.kernel.length,queries:0,combination_branches:0,point_incidence_entries_read:0,subset_incidence_tests:0,translated_coordinates:0,new_circumcenter_tests:0,new_kernel_pairs:0,new_anchor_translations:0};
 function point(p){integer(p,0,n-1,"point");return{id:p,lattice:[Math.floor(p/columns),p%columns],denominator:Q};}
 function circle(id){return s.circles[integer(id,0,s.circles.length-1,"circle")];}
 function selectIn(c,rank){let r=natural(rank,"rank");if(r>=BigInt(c.triple_count))fail("triple rank outside circle");const original=r,positions=[],trace=[];let low=0;for(let slot=0;slot<3;slot++){let selected=-1;const branches=[];for(let j=low;j<=c.members.length-(3-slot);j++){const ct=choose(c.members.length-j-1,2-slot);stats.combination_branches++;branches.push({position:j,count:String(ct)});if(r<ct){selected=j;break;}r-=ct;}if(selected<0)fail("combination selection failed");positions.push(selected);trace.push({slot,selected_position:selected,remaining_rank:String(r),branches});low=selected+1;}return{circle_id:c.id,rank_in_circle:String(original),global_rank:String(BigInt(c.triple_start)+original),point_ids:positions.map(i=>c.members[i]),points:positions.map(i=>point(c.members[i])),center:copy(c.center),trace};}
 function pointSet(ids){if(!Array.isArray(ids)||ids.length>n)fail("point ID array required");const a=ids.slice().sort((a,b)=>a-b);for(let i=0;i<a.length;i++){integer(a[i],0,n-1,"point");if(i&&a[i]===a[i-1])fail("repeated point");}return a;}
 return Object.freeze({
  summary(){stats.queries++;return copy(s.summary);},
  circlesPage(start=0,limit=32){stats.queries++;integer(start,0,s.circles.length,"start");integer(limit,0,128,"limit");return{start,total:s.circles.length,rows:copy(s.circles.slice(start,start+limit)),next:start+limit<s.circles.length?start+limit:null};},
  kernelPage(start=0,limit=32){stats.queries++;integer(start,0,s.kernel.length,"start");integer(limit,0,128,"limit");return{start,total:s.kernel.length,rows:copy(s.kernel.slice(start,start+limit)),next:start+limit<s.kernel.length?start+limit:null};},
  point(p){stats.queries++;return point(p);},
  pointCircles(p){stats.queries++;integer(p,0,n-1,"point");stats.point_incidence_entries_read+=s.point_circles[p].length;return{point:point(p),circle_ids:s.point_circles[p].slice(),count:s.point_circles[p].length};},
  circle(id){stats.queries++;return copy(circle(id));},
  centerLookup(c){stats.queries++;const C=center(signed(c.x),signed(c.y),natural(c.denominator));const id=centerIds.get(key(C));return{center:C,circle_id:id===undefined?null:id};},
  tripleSelect(rank){stats.queries++;const r=natural(rank,"global rank");if(r>=expected)fail("rank outside all determining triples");let lo=0,hi=s.circles.length;while(lo+1<hi){const mid=Math.floor((lo+hi)/2);if(BigInt(s.circles[mid].triple_start)<=r)lo=mid;else hi=mid;}return selectIn(s.circles[lo],String(r-BigInt(s.circles[lo].triple_start)));},
  circleTripleSelect(id,rank){stats.queries++;return selectIn(circle(id),rank);},
  tripleRank(ids){stats.queries++;const a=pointSet(ids);if(a.length!==3)fail("exactly three distinct points");stats.point_incidence_entries_read+=s.point_circles[a[0]].length;const id=s.point_circles[a[0]].find(i=>s.circles[i].members.includes(a[1])&&s.circles[i].members.includes(a[2]));if(id===undefined)return{qualifies:false,point_ids:a,reason:"no saved unit circle contains this triple"};const c=s.circles[id],positions=a.map(p=>c.members.indexOf(p));let rank=0n,low=0;for(let i=0;i<3;i++){for(let j=low;j<positions[i];j++){rank+=choose(c.members.length-j-1,2-i);stats.combination_branches++;}low=positions[i]+1;}return{qualifies:true,point_ids:a,circle_id:id,rank_in_circle:String(rank),global_rank:String(BigInt(c.triple_start)+rank)};},
  intersection(a,b){stats.queries++;const A=circle(a),B=circle(b),set=new Set(B.members);return{circle_ids:[a,b],shared_retained_point_ids:A.members.filter(p=>set.has(p)),scope:"shared points of the retained rectangle, not all real circle intersections"};},
  subsetProfile(ids){stats.queries++;const a=pointSet(ids),set=new Set(a),out=[],hist=new Map();let triples=0n;for(const c of s.circles){const members=[];for(const p of c.members){stats.subset_incidence_tests++;if(set.has(p))members.push(p);}if(members.length>=3){const ct=choose(members.length,3);triples+=ct;out.push({circle_id:c.id,members,triple_count:String(ct)});hist.set(members.length,(hist.get(members.length)||0)+1);}}return{point_ids:a,unit_circles_at_least_three:out.length,determining_triples:String(triples),multiplicity_histogram:[...hist].sort((a,b)=>a[0]-b[0]).map(([points,count])=>({points,count})),circles:out};},
  translateCircle(id,shift){stats.queries++;const c=circle(id);if(!Array.isArray(shift)||shift.length!==2)fail("two rational shifts required");const x=fraction(shift[0]),y=fraction(shift[1]),d=BigInt(c.center.denominator);stats.translated_coordinates+=2;return{circle_id:id,center_x:add([BigInt(c.center.x),d],x),center_y:add([BigInt(c.center.y),d],y),radius:"1",member_ids:c.members.slice(),scope:"common translation of the entire retained rectangle"};},
  translatePoint(p,shift){stats.queries++;const P=point(p);if(!Array.isArray(shift)||shift.length!==2)fail("two rational shifts required");const x=fraction(shift[0]),y=fraction(shift[1]);stats.translated_coordinates+=2;return{id:p,x:add([BigInt(P.lattice[0]),BigInt(Q)],x),y:add([BigInt(P.lattice[1]),BigInt(Q)],y)};},
  statistics(){return copy(stats);}
 });
}
module.exports={VERSION,compileLatticeCircles,openLatticeCircles};
