"use strict";
const VERSION="1.0.0",SCHEMA="commons.projected-prime-dfa.v1";
function fail(s){throw new Error(s);}
function integer(x,a,b,n){if(!Number.isSafeInteger(x)||x<a||x>b)fail(n+" outside limits");return x;}
function copy(x){return JSON.parse(JSON.stringify(x));}
function nat(x,n="integer"){if(typeof x==="number"){if(!Number.isSafeInteger(x)||x<0)fail("unsafe "+n);x=String(x);}if(typeof x!=="string"||!/^(0|[1-9][0-9]*)$/.test(x)||x.length>100)fail("invalid "+n);return BigInt(x);}
function bits(s,empty=false){if(typeof s!=="string"||s.length>8192||!(empty?/^[01]*$/:/^[01]+$/).test(s))fail("binary word required, at most8192 symbols");return s;}
function compileProjection(input){
 if(!input||input.base!==2||!Array.isArray(input.families)||input.families.length<1||input.families.length>4)fail("one to four binary relation families required");
 const L=integer(input.max_length,0,128,"max length"),fs=input.families,qs=new Set();
 const stats={relation_rows_consumed:0,projected_rows:0,new_product_states:0,new_product_arcs:0,coefficient_cells:0,coefficient_additions:0,exception_steps:0,old_relation_graph_construction:0,old_BFS_replayed:0,old_coefficients_consumed:0,old_Thue_Morse_operations:0,integer_values_enumerated:0,primality_tests:0};
 const projections=fs.map(f=>{const q=integer(f.quotient,2,1000,"quotient"),n=integer(f.node_count,1,4096,"relation node count");if(qs.has(q))fail("duplicate quotient");qs.add(q);if(!Array.isArray(f.edges)||f.edges.length!==n||!Array.isArray(f.final)||f.final.length!==n)fail("relation array lengths");integer(f.canonical_start,0,n-1,"canonical start");
  const edges=[],xDigits=[];for(let v=0;v<n;v++){if(!Array.isArray(f.edges[v])||f.edges[v].length!==4||typeof f.final[v]!=="boolean")fail("relation row");stats.relation_rows_consumed++;const to=[],xd=[];for(let b=0;b<2;b++){let target=n,x=-1;for(let a=0;a<2;a++){const w=integer(f.edges[v][2*a+b],-1,n-1,"relation target");if(w>=0){if(x>=0)fail("projection has two x choices for one y digit");target=w;x=a;}}to.push(target);xd.push(x);}edges.push(to);xDigits.push(xd);stats.projected_rows++;}edges.push([n,n]);xDigits.push([-1,-1]);stats.projected_rows++;if(f.final[f.canonical_start]||edges[f.canonical_start][0]!==n)fail("canonical source must reject empty/leading-zero y");return{quotient:q,original_node_count:n,dead:n,start:f.canonical_start,edges,x_digits:xDigits,final:f.final.concat(false)};});
 const p=input.prime_exception_premise;if(!Array.isArray(p)||p.length!==fs.length||new Set(p).size!==p.length||p.some(x=>!qs.has(x)))fail("identify primality premise for each quotient");
 const nodes=[],map=new Map();function intern(states,parent){const k=states.join(",");if(map.has(k))return map.get(k);if(nodes.length>=20000)fail("product state budget");const id=nodes.length;map.set(k,id);let mask=0;for(let i=0;i<states.length;i++)if(projections[i].final[states[i]])mask|=1<<i;nodes.push({id,states:states.slice(),next:[],acceptance_mask:mask,first_parent:parent});stats.new_product_states++;return id;}
 intern(projections.map(x=>x.start),null);for(let v=0;v<nodes.length;v++)for(let b=0;b<2;b++){const to=nodes[v].states.map((s,i)=>projections[i].edges[s][b]);nodes[v].next.push(intern(to,{node:v,bit:b}));stats.new_product_arcs++;}
 const K=(1<<fs.length)-1;if((L+1)*nodes.length*K>1000000)fail("coefficient cell budget");
 const coefficients=[nodes.map(n=>Array.from({length:K},(_,i)=>n.acceptance_mask===i+1?"1":"0"))];stats.coefficient_cells=nodes.length*K;
 for(let l=1;l<=L;l++){const layer=nodes.map(n=>{const a=coefficients[l-1][n.next[0]],b=coefficients[l-1][n.next[1]];return a.map((x,i)=>{stats.coefficient_additions++;return String(BigInt(x)+BigInt(b[i]));});});coefficients.push(layer);stats.coefficient_cells+=nodes.length*K;}
 const primeRows=projections.map(p=>{const word=p.quotient.toString(2),path=[0];let node=0;for(const b of word){node=nodes[node].next[Number(b)];path.push(node);stats.exception_steps++;}return{value:String(p.quotient),word,accepted:nodes[node].acceptance_mask!==0,acceptance_mask:nodes[node].acceptance_mask,path,primality:"identified input premise; no primality test performed"};});
 const lengths=coefficients.map((layer,length)=>({length,exact_support_counts:layer[0].slice(),distinct_values:String(layer[0].reduce((a,x)=>a+BigInt(x),0n))}));
 return{schema:SCHEMA,version:VERSION,input:copy(input),projections,nodes,coefficients,prime_candidates:primeRows,summary:{quotients:projections.map(p=>p.quotient),product_states:nodes.length,product_arcs:2*nodes.length,support_masks:K,max_length:L,at_max_length:lengths[L],accepted_primes:primeRows.filter(x=>x.accepted).map(x=>x.value),length_counts:lengths,prime_classification_scope:"All accepted positive integers, conditional on identified relation semantics and prime quotient premises; no claim about rejected values."},construction:stats};
}
function openProjectedDFA(raw){
 if(typeof raw==="string"){if(raw.length>24000000)fail("snapshot size limit");raw=JSON.parse(raw);}const s=copy(raw);if(!s||s.schema!==SCHEMA||s.version!==VERSION||!s.input||!Array.isArray(s.nodes))fail("invalid snapshot");
 const n=integer(s.nodes.length,1,20000,"node count"),L=integer(s.input.max_length,0,128,"max length"),k=integer(s.input.families.length,1,4,"family count"),K=(1<<k)-1;
 if(!Array.isArray(s.coefficients)||s.coefficients.length!==L+1||!Array.isArray(s.prime_candidates))fail("coefficient/exception arrays");for(let i=0;i<n;i++){const v=s.nodes[i];if(v.id!==i||!Array.isArray(v.next)||v.next.length!==2)fail("DFA node");v.next.forEach(x=>integer(x,0,n-1,"DFA target"));integer(v.acceptance_mask,0,K,"support mask");}
 for(const layer of s.coefficients){if(!Array.isArray(layer)||layer.length!==n)fail("coefficient layer length");for(const row of layer){if(!Array.isArray(row)||row.length!==K)fail("coefficient support length");row.forEach(x=>nat(x,"coefficient"));}}
 const exceptions=s.prime_candidates.filter(x=>x.accepted);for(const e of exceptions){bits(e.word);if(e.word[0]!=="1"||String(BigInt("0b"+e.word))!==e.value)fail("exception word/value");integer(e.acceptance_mask,1,K,"exception mask");}
 const stats={opened_nodes:n,opened_coefficient_cells:(L+1)*n*K,queries:0,coefficient_lookups:0,selection_steps:0,ranking_steps:0,membership_steps:0,exception_comparisons:0,new_factor_divisions:0,new_product_states:0,new_projection_rows:0,new_coefficient_cells:0,old_relation_work:0,old_Thue_Morse_operations:0};
 function opt(o={}){const masks=o.masks===undefined?Array.from({length:K},(_,i)=>i+1):o.masks;if(!Array.isArray(masks)||new Set(masks).size!==masks.length)fail("distinct support masks required");masks.forEach(m=>integer(m,1,K,"support mask"));if(o.composite_only!==undefined&&typeof o.composite_only!=="boolean")fail("composite_only boolean");return{masks:masks.slice(),composite_only:!!o.composite_only};}
 function ways(node,left,prefix,total,o){let ct=0n;for(const mask of o.masks){ct+=BigInt(s.coefficients[left][node][mask-1]);stats.coefficient_lookups++;}if(o.composite_only)for(const e of exceptions){stats.exception_comparisons++;if(e.word.length===total&&e.word.startsWith(prefix)&&o.masks.includes(e.acceptance_mask))ct--;}if(ct<0n)fail("negative saved filtered count");return ct;}
 function selected(node,word,o){return o.masks.includes(s.nodes[node].acceptance_mask)&&(!o.composite_only||!exceptions.some(e=>e.word===word));}
 function trace(word){let node=0;const path=[0];for(const b of word){node=s.nodes[node].next[Number(b)];path.push(node);stats.membership_steps++;}return{node,path};}
 return Object.freeze({
  summary(){stats.queries++;return copy(s.summary);},
  statesPage(start=0,limit=32){stats.queries++;integer(start,0,n,"start");integer(limit,0,128,"limit");return{start,total:n,rows:copy(s.nodes.slice(start,start+limit)),next:start+limit<n?start+limit:null};},
  primeExceptions(){stats.queries++;return copy(s.prime_candidates);},
  count(length,o={}){stats.queries++;integer(length,0,L,"length");const O=opt(o);return{length,options:O,count:String(ways(0,length,"",length,O))};},
  countPrefix(prefix,length,o={}){stats.queries++;bits(prefix,true);integer(length,0,L,"length");if(prefix.length>length)fail("prefix longer than target");let node=0;for(const b of prefix)node=s.nodes[node].next[Number(b)];const O=opt(o);return{prefix,length,options:O,count:String(ways(node,length-prefix.length,prefix,length,O))};},
  select(length,rank,o={}){stats.queries++;integer(length,0,L,"length");const O=opt(o),original=nat(rank,"rank");let r=original,node=0,prefix="";const total=ways(0,length,"",length,O),steps=[];if(r>=total)fail("rank outside family");for(let i=0;i<length;i++){const zero=s.nodes[node].next[0],ct=ways(zero,length-i-1,prefix+"0",length,O),bit=r<ct?0:1;if(bit)r-=ct;steps.push({position:i,node,zero_count:String(ct),bit,rank_after:String(r)});node=s.nodes[node].next[bit];prefix+=bit;stats.selection_steps++;}if(r!==0n||!selected(node,prefix,O))fail("saved selection ended outside family");return{length,rank:String(original),count:String(total),word:prefix,value:String(BigInt("0b"+prefix)),acceptance_mask:s.nodes[node].acceptance_mask,trace:steps};},
  rank(word,o={}){stats.queries++;bits(word);integer(word.length,1,L,"length");const O=opt(o);let node=0,prefix="",r=0n;const steps=[];for(let i=0;i<word.length;i++){const bit=Number(word[i]);let skip=0n;if(bit)skip=ways(s.nodes[node].next[0],word.length-i-1,prefix+"0",word.length,O);r+=skip;steps.push({position:i,node,bit,skipped:String(skip)});node=s.nodes[node].next[bit];prefix+=bit;stats.ranking_steps++;}if(!selected(node,word,O))return{valid:false,word,acceptance_mask:s.nodes[node].acceptance_mask,reason:"word outside selected support/composite family"};return{valid:true,word,rank:String(r),acceptance_mask:s.nodes[node].acceptance_mask,trace:steps};},
  countUpTo(word,o={}){stats.queries++;bits(word);if(word[0]!=="1")fail("canonical positive bound required");integer(word.length,1,L,"bound length");const O=opt(o);let ct=0n;for(let l=1;l<word.length;l++)ct+=ways(0,l,"",l,O);let node=0,prefix="";for(let i=0;i<word.length;i++){const bit=Number(word[i]);if(bit)ct+=ways(s.nodes[node].next[0],word.length-i-1,prefix+"0",word.length,O);node=s.nodes[node].next[bit];prefix+=bit;}if(selected(node,word,O))ct++;return{bound_word:word,bound:String(BigInt("0b"+word)),options:O,count:String(ct)};},
  classify(word){stats.queries++;bits(word);const tr=trace(word),mask=s.nodes[tr.node].acceptance_mask;if(mask===0)return{word,accepted:false,status:"outside this language; no primality conclusion",terminal:tr.node,path:tr.path};const value=BigInt("0b"+word),exception=exceptions.find(e=>e.word===word);if(exception)return{word,value:String(value),accepted:true,acceptance_mask:mask,status:"prime under identified input premise",prime:exception.value,terminal:tr.node,path:tr.path};let i=0;while(!(mask&(1<<i)))i++;const q=BigInt(s.input.families[i].quotient);stats.new_factor_divisions++;const x=value/q,remainder=value%q;if(x<=1n||remainder!==0n)fail("inherited factor semantics contradicted");return{word,value:String(value),accepted:true,acceptance_mask:mask,status:"composite",factor:String(q),cofactor:String(x),remainder:String(remainder),terminal:tr.node,path:tr.path};},
  statistics(){return copy(stats);}
 });
}
module.exports={VERSION,compileProjection,openProjectedDFA};
